version: '3.9'

services:
    postgres_db:
        image: postgres:16-alpine
        env_file:
            - ./env/.db.env
        volumes:
            - postgres_data:/var/lib/postgresql/data
        ports:
            - '5432:5432'
        restart: always

volumes:
    postgres_data:
